spring.application.name=livros
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:h2:mem:livrosdb
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
